In [18]:
%matplotlib inline
import pandas as pd
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
MACRO_MARKET_DATA = "../data/MarketData_Macro.csv"

In [19]:
df_macro = pd.read_csv(MACRO_MARKET_DATA)
df_macro.columns

Index(['DateKey', 'SSE', 'DAX', 'EUROSTOXX', 'VSTOXX', 'FTSE100', 'HSI',
       'NIKKEI', 'DOWJONES_INDU', 'SP500',
       ...
       'Swap_TRY2Y', 'Swap_TRY5Y', 'Swap_USD10Y', 'Swap_USD2Y', 'Swap_USD30Y',
       'Swap_USD5Y', 'Swap_ZAR10Y', 'Swap_ZAR2Y', 'Swap_ZAR30Y', 'Swap_ZAR5Y'],
      dtype='object', length=112)

In [17]:
print("Overview")
print(df_macro.head(10))
print(df_macro.describe())

print()
print("Nan Values")
print(df_macro.isnull().sum())

Overview
    DateKey       SSE      DAX  EUROSTOXX   VSTOXX  FTSE100       HSI  \
0  20150101       NaN      NaN        NaN      NaN      NaN       NaN
1  20150102       NaN  9764.73    3139.44  26.2531  6547.80  23857.82
2  20150105  3350.519  9473.16    3023.14  29.6236  6417.16  23721.32
3  20150106  3351.446  9469.66    3007.91  28.8317  6366.51  23485.41
4  20150107  3373.954  9518.18    3026.79  28.1715  6419.83  23681.26
5  20150108  3293.456  9837.61    3135.08  25.9087  6569.96  23835.53
6  20150109  3285.412  9648.50    3042.90  28.7787  6501.14  23919.95
7  20150112  3229.316  9781.90    3084.18  29.7249  6501.42  24026.46
8  20150113  3235.301  9941.00    3133.86  28.5404  6542.20  24215.97
9  20150114  3222.437  9817.08    3089.67  29.4845  6388.46  24112.60

     NIKKEI  DOWJONES_INDU    SP500     ...      Swap_TRY2Y  Swap_TRY5Y  \
0       NaN            NaN      NaN     ...       10.069276    9.915120
1       NaN       17832.99  2058.20     ...       10.151881    9.976101
2  17408.71       17501.65  2020.58     ...        9.720274    9.575104
3  16883.19       17371.64  2002.61     ...        9.446627    9.301924
4  16885.33       17584.52  2025.90     ...        9.315702    9.221503
5  17167.10       17907.87  2062.14     ...        9.235417    9.191143
6  17197.73       17737.37  2044.81     ...        9.195008    9.160945
7  17142.72       17640.84  2028.26     ...        9.054825    8.990076
8  17087.71       17613.68  2023.03     ...        8.952749    8.887882
9  16795.96       17427.09  2011.27     ...        8.891734    8.836789

   Swap_USD10Y  Swap_USD2Y  Swap_USD30Y  Swap_USD5Y  Swap_ZAR10Y  Swap_ZAR2Y  \
0     2.295037         NaN     2.712112    1.774452     7.963276    6.856526
1     2.236910    0.893242     2.647499    1.746344     7.940000    6.840000
2     2.148063    0.891052     2.549802    1.695687     7.840000    6.780000
3     2.066794    0.858954     2.457286    1.620356     7.670000    6.660000
4     2.063763    0.845034     2.454874    1.612189     7.590000    6.550000
5     2.135254    0.844362     2.540008    1.640353     7.527500    6.470000
6     2.089948    0.803262     2.495326    1.588730     7.510000    6.440000
7     2.028743    0.778192     2.429074    1.529680     7.450000    6.410000
8     2.001301    0.758112     2.409828    1.499076     7.460000    6.430000
9     1.947211    0.717373     2.374120    1.440914     7.360000    6.370000

   Swap_ZAR30Y  Swap_ZAR5Y
0     8.331874    7.403867
1     8.310000    7.390000
2     8.210000    7.300000
3     8.040000    7.150000
4     7.960000    7.060000
5     7.897500    6.962500
6     7.880000    6.940000
7     7.820000    6.880000
8     7.820000    6.880000
9     7.720000    6.780000

[10 rows x 112 columns]
            DateKey          SSE           DAX    EUROSTOXX      VSTOXX  \
count  8.770000e+02   875.000000    876.000000   876.000000  876.000000
mean   2.016278e+07  3310.487480  11355.682289  3331.244218   20.297314
std    9.840161e+03   413.973635   1136.826936   255.117381    5.981892
min    2.015010e+07  2655.661000   8752.870000  2680.350000   10.678300
25%    2.015110e+07  3085.148000  10377.267500  3069.882500   15.274250
50%    2.016091e+07  3222.167000  11448.480000  3407.065000   19.900550
75%    2.017071e+07  3381.246500  12299.285000  3553.512500   23.933075
max    2.018051e+07  5166.350000  13559.600000  3828.780000   40.803000

           FTSE100           HSI        NIKKEI  DOWJONES_INDU        SP500  \
count   876.000000    876.000000    875.000000     876.000000   876.000000
mean   6873.943179  24726.487500  19148.118977   19709.190297  2256.015862
std     515.046544   3406.147361   2008.348280    2709.444089   245.959213
min    5536.970000  18319.580000  14952.020000   15660.180000  1829.080000
25%    6401.537500  22137.215000  17348.850000   17731.567500  2076.547500
50%    6936.395000  24113.730000  19344.150000   18330.890000  2162.430000
75%    7327.522500  27525.542500  20261.175000   21487.745000  2438.467500
max    7778.640000  33154.120000  24124.150000   26616.710000  2872.870000

          ...      Swap_TRY2Y  Swap_TRY5Y  Swap_USD10Y  Swap_USD2Y  \
count     ...      877.000000  877.000000   877.000000  876.000000
mean      ...       11.873001   11.496660     2.137045    1.320768
std       ...        1.715101    1.314005     0.389535    0.543970
min       ...        8.499006    8.594088     1.252937    0.669068
25%       ...       10.737509   10.556425     1.921299    0.893981
50%       ...       11.820483   11.555321     2.196584    1.047324
75%       ...       12.384860   11.927217     2.352726    1.597077
max       ...       17.894594   16.105111     3.055699    2.784215

       Swap_USD30Y  Swap_USD5Y  Swap_ZAR10Y  Swap_ZAR2Y  Swap_ZAR30Y  \
count   877.000000  877.000000   877.000000  877.000000   877.000000
mean      2.468450    1.755107     8.180788    7.216463     8.185374
std       0.318286    0.455610     0.438166    0.426848     0.396605
min       1.665022    0.933159     6.930000    6.060000     7.290000
25%       2.329321    1.383992     7.860000    6.890000     7.865000
50%       2.530799    1.731862     8.135000    7.150000     8.085000
75%       2.658366    1.997856     8.430000    7.540000     8.462500
max       3.088962    2.958393     9.740000    8.315000     9.765000

       Swap_ZAR5Y
count  877.000000
mean     7.683478
std      0.469260
min      6.370000
25%      7.320000
50%      7.670000
75%      7.932500
max      9.240000

[8 rows x 112 columns]

Nan Values
DateKey              0
SSE                  2
DAX                  1
EUROSTOXX            1
VSTOXX               1
FTSE100              1
HSI                  1
NIKKEI               2
DOWJONES_INDU        1
SP500                1
VIX                  0
FX_USD.ARS           0
FX_USD.AUD           0
FX_USD.BRL           0
FX_USD.CAD           0
FX_USD.CHF           0
FX_USD.CNO           0
FX_USD.CNY           0
FX_USD.EUR           0
FX_USD.GBP           0
FX_USD.HKD           0
FX_USD.IDR           0
FX_USD.JPY           0
FX_USD.NOK           0
FX_USD.SGD           0
FX_USD.TRY           0
FX_USD.ZAR           0
MoneyMarket_ARS3M    0
MoneyMarket_AUD3M    0
MoneyMarket_CAD3M    0
                    ..
Swap_HKD2Y           0
Swap_HKD30Y          1
Swap_HKD5Y           0
Swap_IDR10Y          0
Swap_IDR2Y           0
Swap_IDR30Y          0
Swap_IDR5Y           0
Swap_JPY10Y          0
Swap_JPY2Y           2
Swap_JPY30Y          0
Swap_JPY5Y           0
Swap_NOK10Y          0
Swap_NOK2Y           1
Swap_NOK30Y          0
Swap_NOK5Y           0
Swap_SGD10Y          1
Swap_SGD2Y           1
Swap_SGD30Y          1
Swap_SGD5Y           1
Swap_TRY10Y          0
Swap_TRY2Y           0
Swap_TRY5Y           0
Swap_USD10Y          0
Swap_USD2Y           1
Swap_USD30Y          0
Swap_USD5Y           0
Swap_ZAR10Y          0
Swap_ZAR2Y           0
Swap_ZAR30Y          0
Swap_ZAR5Y           0
Length: 112, dtype: int64